$appName = "app-aludemo"
$TenantId = ""
Connect-AzureAd -TenantId $TenantId
$Tenant = Get-AzureADTenantDetail
$TenantDomain = $Tenant.VerifiedDomains[0].Name
$appURI = "https://$appName.$TenantDomain"
$appHomePageUrl = "https://$appName.azurewebsites.net"
$appReplyURLs = @($appURI, $appHomePageURL)
 
# Create new AppRole object
$newAppRole = [Microsoft.Open.AzureAD.Model.AppRole]::new()
$newAppRole.AllowedMemberTypes = New-Object System.Collections.Generic.List[string]
$newAppRole.AllowedMemberTypes.Add("Application")
$newAppRole.DisplayName = "Applications"
$newAppRole.Description = "Applications can call API with all rights"
$newAppRole.Value = "ReadWrite.All"
$newAppRole.Id = [Guid]::NewGuid().ToString()
$newAppRole.IsEnabled = $true
 
$myApp = New-AzureADApplication -DisplayName $appName -IdentifierUris $appURI -Homepage $appHomePageUrl -ReplyUrls $appReplyURLs -AppRoles $newAppRole
 
# Application Password Credentials (ClientSecret)
$startDate = Get-Date
$endDate = $startDate.AddYears(1)
$aadAppKeyPwd = New-AzureADApplicationPasswordCredential -ObjectId $myApp.ObjectId -CustomKeyIdentifier "Generated by PowerShell"
 
Write-Host "Application $($myApp.ObjectId) Secret: $($aadAppKeyPwd.Value)"
 
